# Generated by Django 3.1.7 on 2021-03-15 14:52

from django.db import migrations


def default_data(apps, schema_editor):
    Hall = apps.get_model("seminar", "Hall")
    hall_data = {'A': 50, 'B': 100,'C': 200, 'D': 350, 'E': 500, 'F': 1000}
    halls = list()
    for hall_name,capacity in hall_data.items():
        halls.append(Hall(hall_name = hall_name, capacity = capacity))
    Hall.objects.bulk_create(halls)
    
def delete_default_data(apps, schema_editor):
    Hall = apps.get_model("seminar", "Hall")
    Hall.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('seminar', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_data, delete_default_data),
    ]